// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qixdgkmwhknfeehwhdpa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpeGRna213aGtuZmVlaHdoZHBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0OTM3NzksImV4cCI6MjA1MzA2OTc3OX0.7HYZ08yhfp3VAf_D6NrqhGf7WdbWZaVCTnFne4dwlRY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);